=== AlexanderB1290/scafacos/test/generic/systems/scafacos_test.dtd
<!ELEMENT scafacos_test (method?, configuration*) >
<!ELEMENT method (param*) >
<!ELEMENT param EMPTY >
<!ELEMENT configuration (duplicate | generate* | particle*) >
<!ELEMENT duplicate (particle*) >
<!ELEMENT particle EMPTY >
<!ELEMENT generate (positions, charges, potentials?, field?) >
<!ELEMENT positions EMPTY >
<!ELEMENT charges EMPTY >
<!ELEMENT potentials EMPTY >
<!ELEMENT field EMPTY >

<!ATTLIST scafacos_test name CDATA #REQUIRED>
<!ATTLIST scafacos_test description CDATA #REQUIRED>
<!ATTLIST scafacos_test reference_method CDATA #IMPLIED>
<!ATTLIST scafacos_test error_potential CDATA "1.0">
<!ATTLIST scafacos_test error_field CDATA "1.0">

<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #IMPLIED>
<!ATTLIST param value0 CDATA #IMPLIED>
<!ATTLIST param value1 CDATA #IMPLIED>
<!ATTLIST param value2 CDATA #IMPLIED>

<!ATTLIST configuration offset CDATA #IMPLIED>
<!ATTLIST configuration box_a CDATA #IMPLIED>
<!ATTLIST configuration box_b CDATA #IMPLIED>
<!ATTLIST configuration box_c CDATA #IMPLIED>
<!ATTLIST configuration periodicity CDATA #IMPLIED>
<!ATTLIST configuration epsilon CDATA #IMPLIED>
<!ATTLIST configuration decomposition CDATA #IMPLIED>

<!ATTLIST duplicate times CDATA #REQUIRED>
<!ATTLIST duplicate rescale CDATA "1">

<!ATTLIST particle position CDATA #REQUIRED>
<!ATTLIST particle q CDATA "0.0">
<!ATTLIST particle potential CDATA #IMPLIED>
<!ATTLIST particle field CDATA #IMPLIED>
<!ATTLIST particle node CDATA #IMPLIED>

<!ATTLIST generate nlocal CDATA #IMPLIED>
<!ATTLIST generate ntotal CDATA #IMPLIED>

<!ATTLIST positions type CDATA #REQUIRED>
<!ATTLIST positions shape CDATA #IMPLIED>

<!ATTLIST charges type CDATA #REQUIRED>
<!ATTLIST charges value CDATA "1.0">

<!ATTLIST potentials type CDATA #REQUIRED>
<!ATTLIST potentials value CDATA "0.0">

<!ATTLIST field type CDATA #REQUIRED>
<!ATTLIST field value CDATA "0.0 0.0 0.0">

=== AlexanderB1290/scafacos/test/generic/systems/generic/generator_test.xml
<?xml version="1.0" ?>
<!DOCTYPE scafacos_test  SYSTEM '../scafacos_test.dtd'>
<scafacos_test description="Testing particle generation." name="generate_test">
  <configuration box_a="10.0 0.0 0.0" box_b="0.0 10.0 0.0" box_c="0.0 0.0 10.0" epsilon="metallic" periodicity="0 0 0" decomposition="atomistic">
    <generate nlocal="100">
      <positions type="random" shape="box"/>
      <charges type="const" value="1.0"/>
    </generate>
    <generate ntotal="200">
      <positions type="random" shape="box"/>
      <charges type="const" value="1.0"/>
    </generate>
    <generate ntotal="10">
      <positions type="hammersley" shape="box"/>
      <charges type="const" value="1.0"/>
    </generate>
    <generate ntotal="10">
      <positions type="halton" shape="box"/>
      <charges type="const" value="1.0"/>
    </generate>
  </configuration>
</scafacos_test>

=== AlexanderB1290/scafacos/test/generic/systems/generic/duplicate_test.xml
<?xml version="1.0" ?>
<!DOCTYPE scafacos_test SYSTEM '../scafacos_test.dtd'>
<scafacos_test description="Testing particle duplication." name="duplicate_test">
  <configuration box_a="1.0 0.0 0.0" box_b="0.0 1.0 0.0" box_c="0.0 0.0 1.0" epsilon="metallic" periodicity="1 1 1" decomposition="all_on_master">
    <particle position="0.25 0.25 0.25" q=" 1.0"/>
    <particle position="0.25 0.25 0.75" q="-1.0"/>
    <particle position="0.25 0.75 0.25" q="-1.0"/>
    <particle position="0.25 0.75 0.75" q=" 1.0"/>
    <particle position="0.75 0.25 0.25" q="-1.0"/>
    <particle position="0.75 0.25 0.75" q=" 1.0"/>
    <particle position="0.75 0.75 0.25" q=" 1.0"/>
    <particle position="0.75 0.75 0.75" q="-1.0"/>
  </configuration>
  <configuration box_a="1.0 0.0 0.0" box_b="0.0 1.0 0.0" box_c="0.0 0.0 1.0" epsilon="metallic" periodicity="1 1 1" decomposition="atomistic">
    <duplicate times="2 2 2" rescale="1">
      <particle position="0.25 0.25 0.25" q=" 1.0"/>
      <particle position="0.25 0.25 0.75" q="-1.0"/>
      <particle position="0.25 0.75 0.25" q="-1.0"/>
      <particle position="0.25 0.75 0.75" q=" 1.0"/>
      <particle position="0.75 0.25 0.25" q="-1.0"/>
      <particle position="0.75 0.25 0.75" q=" 1.0"/>
      <particle position="0.75 0.75 0.25" q=" 1.0"/>
      <particle position="0.75 0.75 0.75" q="-1.0"/>
    </duplicate>
  </configuration>
  <configuration box_a="1.0 0.0 0.0" box_b="0.0 1.0 0.0" box_c="0.0 0.0 1.0" epsilon="metallic" periodicity="1 1 1" decomposition="random">
    <duplicate times="3 3 3" rescale="1">
      <particle position="0.25 0.25 0.25" q=" 1.0"/>
      <particle position="0.25 0.25 0.75" q="-1.0"/>
      <particle position="0.25 0.75 0.25" q="-1.0"/>
      <particle position="0.25 0.75 0.75" q=" 1.0"/>
      <particle position="0.75 0.25 0.25" q="-1.0"/>
      <particle position="0.75 0.25 0.75" q=" 1.0"/>
      <particle position="0.75 0.75 0.25" q=" 1.0"/>
      <particle position="0.75 0.75 0.75" q="-1.0"/>
    </duplicate>
  </configuration>
  <configuration box_a="1.0 0.0 0.0" box_b="0.0 1.0 0.0" box_c="0.0 0.0 1.0" epsilon="metallic" periodicity="1 1 1" decomposition="domain">
    <duplicate times="4 4 4" rescale="1">
      <particle position="0.25 0.25 0.25" q=" 1.0"/>
      <particle position="0.25 0.25 0.75" q="-1.0"/>
      <particle position="0.25 0.75 0.25" q="-1.0"/>
      <particle position="0.25 0.75 0.75" q=" 1.0"/>
      <particle position="0.75 0.25 0.25" q="-1.0"/>
      <particle position="0.75 0.25 0.75" q=" 1.0"/>
      <particle position="0.75 0.75 0.25" q=" 1.0"/>
      <particle position="0.75 0.75 0.75" q="-1.0"/>
    </duplicate>
  </configuration>
</scafacos_test>

=== AlexanderB1290/scafacos/test/generic/systems/generic/parameter_test.xml
<?xml version="1.0" ?>
<!DOCTYPE scafacos_test  SYSTEM '../scafacos_test.dtd'>
<scafacos_test description="Testing particle generation." name="generate_test">
  <method>
    <param name="require_virial" value="1"/>
    <param name="direct_set_periodic_images" value="1,1,1"/>
    <param name="mmm2d_set_dielectric_contrasts" value0="0.999" value1="0.777"/>
  </method>
  <configuration box_a="10.0 0.0 0.0" box_b="0.0 10.0 0.0" box_c="0.0 0.0 10.0" epsilon="metallic" periodicity="0 0 0" decomposition="atomistic">
    <generate nlocal="100">
      <positions type="random" shape="box"/>
      <charges type="const" value="1.0"/>
    </generate>
  </configuration>
</scafacos_test>
